"""Generator-confound check for the diff+adversarial-training result chain
(RESEARCH_PROPOSAL.md direction 16): every adversarial triple used so far,
both training (results/llm_redteam_train_pool.json) and held-out test
(results/llm_redteam_results.json), was generated by the SAME model
(DeepSeek) via the SAME prompt templates (scripts/llm_redteam_verifier.py).
A verifier fine-tuned on DeepSeek-written hard negatives might have learned
DeepSeek's particular way of writing a negation/entity-swap/etc. sentence,
not the underlying failure mode -- this was flagged as an open risk in
social_media/reddit/post_12 itself and never checked.

This script generates an independent test set with a DIFFERENT model
(OpenAI GPT, via the Chat Completions API) using the EXACT SAME five
CATEGORY_PROMPTS and JSON_INSTRUCTION text as scripts/llm_redteam_verifier.py
(copied verbatim, not paraphrased, so any difference in the resulting triples
comes from the generator, not a prompt-wording confound). Embedding and
similarity filtering (all-MiniLM-L6-v2, tau_low=0.80) also match exactly.

Usage:
    python scripts/generate_openai_redteam_set.py --n-per-category 20 --rounds 1
"""

import argparse
import json
import os
import sys
import time
from concurrent.futures import ThreadPoolExecutor, as_completed
from pathlib import Path

import numpy as np
import requests
from dotenv import load_dotenv

sys.path.insert(0, str(Path(__file__).resolve().parent.parent))

OPENAI_URL = "https://api.openai.com/v1/chat/completions"
TAU_LOW = 0.80

# Copied verbatim from scripts/llm_redteam_verifier.py so the only variable
# between that run and this one is the generator model, not the prompt wording.
CATEGORY_PROMPTS = {
    "negation": (
        "Generate {n} triples for testing a semantic-cache verifier's robustness to NEGATION. "
        "Each triple has: query_a (a customer support / general question), query_b (a query that looks "
        "almost identical to query_a in wording and topic, but differs by a negation -- e.g. adds 'not', "
        "'don't', 'never', or flips 'keep' vs 'cancel'), and answer_b (a specific, correct answer to "
        "query_b ONLY -- it must be WRONG if given in response to query_a). The two queries should be "
        "similar enough in surface wording that a similarity-based cache might confuse them, but the "
        "negation must make the correct answer genuinely different, not just phrased differently."
    ),
    "action_verb": (
        "Generate {n} triples for testing a semantic-cache verifier's robustness to ACTION-VERB SWAPS. "
        "Each triple has: query_a and query_b about the same object/service (e.g. a subscription, an "
        "order, an account) but with a DIFFERENT ACTION VERB (cancel vs pause vs downgrade vs renew vs "
        "refund vs delete), and answer_b, a specific correct answer to query_b ONLY that would be WRONG "
        "advice if given for query_a (e.g. steps to cancel are wrong if the user actually wanted to pause). "
        "Keep the object/service identical between query_a and query_b so only the verb differs."
    ),
    "direction": (
        "Generate {n} triples for testing a semantic-cache verifier's robustness to REVERSED DIRECTION. "
        "Each triple has: query_a and query_b that use the SAME VERB and the same two nouns/formats, but "
        "in OPPOSITE DIRECTION (e.g. 'convert audio to video' vs 'convert video to audio', 'translate "
        "English to French' vs 'translate French to English', 'import CSV to database' vs 'export database "
        "to CSV'), and answer_b, a specific correct answer to query_b ONLY that would be procedurally WRONG "
        "if given for query_a (reversed steps/tools)."
    ),
    "entity_swap": (
        "Generate {n} triples for testing a semantic-cache verifier's robustness to NAMED-ENTITY SWAPS. "
        "Each triple has: query_a and query_b that are IDENTICAL in sentence structure and topic but ask "
        "about a DIFFERENT specific named entity (different person, product model, city, or brand -- e.g. "
        "'George H.W. Bush' vs 'George W. Bush', 'iPhone 14' vs 'iPhone 15', 'Paris, Texas' vs 'Paris, "
        "France'), and answer_b, a specific factual answer about query_b's entity ONLY that would be "
        "factually WRONG if given for query_a's entity."
    ),
    "quantity_swap": (
        "Generate {n} triples for testing a semantic-cache verifier's robustness to QUANTITY/PARAMETER "
        "SWAPS. Each triple has: query_a and query_b that are identical except for a numeric quantity, "
        "percentage, date, or duration (e.g. 'save 10% on my bill' vs 'save 50% on my bill', 'refund within "
        "30 days' vs 'refund within 90 days'), and answer_b, a specific correct answer to query_b's exact "
        "number that would be WRONG (a different eligibility/outcome/amount) if given for query_a's number."
    ),
}

JSON_INSTRUCTION = (
    "\n\nReturn ONLY a JSON array (no markdown fences, no commentary) of exactly {n} objects, each with "
    'keys "query_a", "query_b", "answer_b" (all strings). Make the pairs realistic customer-support / '
    "general-Q&A style queries, similar in length and register to what a real user would type."
)


def call_openai_generate(api_key: str, category: str, n: int, model: str) -> list[dict]:
    prompt = CATEGORY_PROMPTS[category].format(n=n) + JSON_INSTRUCTION.format(n=n)
    headers = {"Authorization": f"Bearer {api_key}", "Content-Type": "application/json"}
    payload = {
        "model": model,
        "messages": [{"role": "user", "content": prompt}],
        "temperature": 0.9,
    }
    resp = requests.post(url=OPENAI_URL, headers=headers, json=payload, timeout=120)
    resp.raise_for_status()
    content = resp.json()["choices"][0]["message"]["content"].strip()
    if content.startswith("```"):
        content = content.strip("`")
        if content.startswith("json"):
            content = content[4:]
    triples = json.loads(content)
    for t in triples:
        t["category"] = category
    return triples


def cosine_sim(a, b) -> float:
    a, b = np.asarray(a), np.asarray(b)
    return float(a @ b / (np.linalg.norm(a) * np.linalg.norm(b) + 1e-12))


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("--n-per-category", type=int, default=20)
    parser.add_argument("--rounds", type=int, default=1)
    parser.add_argument("--model", default="gpt-4o-mini")
    parser.add_argument("--max-workers", type=int, default=8,
                        help="Concurrent request workers. Kept conservative by default since this key's "
                             "actual rate-limit tier is unknown; raise it if requests aren't getting "
                             "throttled (watch for 429s in the FAILED lines).")
    parser.add_argument("--output", default="results/openai_redteam_generated.json")
    args = parser.parse_args()

    load_dotenv()
    api_key = os.environ.get("OPENAI_API_KEY")
    if not api_key:
        raise SystemExit("OPENAI_API_KEY not found (checked .env and environment).")

    jobs = [(round_i, category) for round_i in range(1, args.rounds + 1) for category in CATEGORY_PROMPTS]
    print(f"[{time.strftime('%H:%M:%S')}] Generating {args.n_per_category} triples per category x "
          f"{args.rounds} round(s) = {len(jobs)} concurrent requests (max_workers={args.max_workers}) "
          f"via {args.model}...", flush=True)

    all_triples = []
    with ThreadPoolExecutor(max_workers=args.max_workers) as pool:
        futures = {
            pool.submit(call_openai_generate, api_key, category, args.n_per_category, args.model): (round_i, category)
            for round_i, category in jobs
        }
        for fut in as_completed(futures):
            round_i, category = futures[fut]
            try:
                triples = fut.result()
            except Exception as e:
                print(f"  [round {round_i}][{category}] generation FAILED: {e}", flush=True)
                continue
            print(f"  [round {round_i}][{category}] generated {len(triples)} triples", flush=True)
            all_triples.extend(triples)

    if not all_triples:
        raise SystemExit("No triples generated -- aborting.")

    print(f"\n[{time.strftime('%H:%M:%S')}] Embedding {len(all_triples)} query_a/query_b pairs "
          f"with all-MiniLM-L6-v2 (matches the DeepSeek pipeline's embedder)...", flush=True)
    from sentence_transformers import SentenceTransformer

    embedder = SentenceTransformer("sentence-transformers/all-MiniLM-L6-v2")
    texts_a = [t["query_a"] for t in all_triples]
    texts_b = [t["query_b"] for t in all_triples]
    emb_a = embedder.encode(texts_a, convert_to_numpy=True, show_progress_bar=False)
    emb_b = embedder.encode(texts_b, convert_to_numpy=True, show_progress_bar=False)
    for t, ea, eb in zip(all_triples, emb_a, emb_b):
        t["similarity"] = cosine_sim(ea, eb)

    qualifying = [t for t in all_triples if t["similarity"] >= TAU_LOW]
    print(f"  {len(qualifying)}/{len(all_triples)} pairs cleared tau_low={TAU_LOW}", flush=True)

    out_path = Path(args.output)
    out_path.parent.mkdir(parents=True, exist_ok=True)
    out_path.write_text(
        json.dumps({"generator": args.model, "n_generated_total": len(all_triples),
                    "n_qualifying": len(qualifying), "all_triples": all_triples}, indent=2),
        encoding="utf-8",
    )
    print(f"\nWrote {out_path}")


if __name__ == "__main__":
    main()
